applications={
    "vs code":"C:\AssistantPaths\Visual Studio Code.lnk",
    "visual studio":"C:\AssistantPaths\Visual Studio 2022.lnk",
    "eclipse":"C:\AssistantPaths\eclipse.lnk",
    "calculator":"C:\AssistantPaths\calc - Shortcut.lnk",
    "pycharm":"C:\AssistantPaths\PyCharm Community Release.lnk",
    "powerpoint":"C:\AssistantPaths\PowerPoint.lnk",
    "word":"C:\AssistantPaths\Word.lnk",
    "excel":"C:\AssistantPaths\Excel.lnk",
    "zoom":"C:\AssistantPaths\Zoom.lnk",
    "microsoft teams":"C:\AssistantPaths\Microsoft Teams classic (work or school).lnk",
    "recycle bin":"C:\AssistantPaths\Recycle Bin.lnk",
    "mongodb":"C:\AssistantPaths\MongoDBCompass.lnk",
    "powershell":"C:\AssistantPaths\Windows PowerShell.lnk",
    "command prompt":"C:\AssistantPaths\Command Prompt.lnk",
    "postman":"C:\AssistantPaths\Postman.lnk",
    "notes":"C:\AssistantPaths\Sticky Notes (new).lnk",
    "one note":"C:\AssistantPaths\OneNote.lnk",
    "one drive":"C:\AssistantPaths\OneDrive.lnk",
    "grammarly":"C:\AssistantPaths\Grammarly.lnk",
    "chrome browser":"C:\AssistantPaths\Google Chrome.lnk",
    "edge browser":"C:\AssistantPaths\Microsoft Edge.lnk",
    "file explorer":"C:\AssistantPaths\File Explorer.lnk",
    "figma":"C:\AssistantPaths\Figma.lnk",
    "cursor":"C:\AssistantPaths\Cursor.lnk",
    "arduino":"C:\AssistantPaths\Arduino IDE.lnk",
    "amazon":"C:\AssistantPaths\Amazon.com.lnk",
    "adobe":"C:\AssistantPaths\Adobe Acrobat.lnk",
}

sites = {
    "youtube": "https://www.youtube.com",
    "wikipedia": "https://www.wikipedia.org",
    "google": "https://www.google.com",
    "facebook": "https://www.facebook.com",
    "twitter": "https://www.twitter.com",
    "instagram": "https://www.instagram.com",
    "linkedin": "https://www.linkedin.com",
    "reddit": "https://www.reddit.com",
    "github website": "https://www.github.com",
    "amazon": "https://www.amazon.com",
    "netflix": "https://www.netflix.com",
    "spotify": "https://www.spotify.com",
    "news": "https://www.cnn.com",
    "email": "https://www.gmail.com",
    "twitch": "https://www.twitch.tv",
    "pinterest": "https://www.pinterest.com",
    "tiktok": "https://www.tiktok.com",
    "microsoft": "https://www.microsoft.com",
    "apple": "https://www.apple.com",
    "ebay": "https://www.ebay.com",
    "stackoverflow": "https://stackoverflow.com",
    "medium": "https://medium.com",
    "quora": "https://www.quora.com",
    "weather": "https://www.weather.com",
    "imdb": "https://www.imdb.com",
    "bbc": "https://www.bbc.com",
    "nytimes": "https://www.nytimes.com",
    "coursera": "https://www.coursera.org",
    "udemy": "https://www.udemy.com",
    "zoom": "https://zoom.us",
    "dropbox": "https://www.dropbox.com",
    "google drive": "https://drive.google.com",
    "google maps": "https://maps.google.com",
    "bing": "https://www.bing.com",
    "stackoverflow": "https://stackoverflow.com",
    "khan academy": "https://www.khanacademy.org",
    "reddit": "https://www.reddit.com",
    "quora": "https://www.quora.com",
    "twitch": "https://www.twitch.tv",
    "discord": "https://discord.com",
    "slack": "https://slack.com",
    "notion": "https://www.notion.so",
    "canva": "https://www.canva.com",
    "figma": "https://www.figma.com",
}